-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 18, 2023 at 06:28 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.0.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `serverside`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `recipe_id` int(250) NOT NULL,
  `recipe_name` varchar(250) NOT NULL,
  `recipe_ingredients` varchar(1000) NOT NULL,
  `recipe_instructions` varchar(2000) NOT NULL,
  `recipe_image` blob DEFAULT NULL,
  `recipe_timestamp` timestamp NOT NULL DEFAULT current_timestamp(),
  `recipe_updated` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `recipe_sources` varchar(250) NOT NULL,
  `categories_id` int(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`recipe_id`, `recipe_name`, `recipe_ingredients`, `recipe_instructions`, `recipe_image`, `recipe_timestamp`, `recipe_updated`, `recipe_sources`, `categories_id`) VALUES
(107, 'Gochujang Chicken Wings', 'Coating:\r\n\r\n2 tablespoons baking powder\r\n\r\n1 teaspoon salt\r\n\r\n1 teaspoon freshly ground black pepper\r\n\r\n1 teaspoon garlic powder\r\n\r\n½ teaspoon onion powder\r\n\r\n2 pounds chicken wings, separated at the joint\r\n\r\nSauce:\r\n\r\n3 tablespoons gochujang (Korean hot and sweet pepper paste), or to taste\r\n\r\n2 tablespoons reduced-sodium soy sauce\r\n\r\n1 ½ tablespoons honey\r\n\r\n1 tablespoon rice vinegar\r\n\r\n1 teaspoon sesame oil\r\n\r\n1 teaspoon ground ginger\r\n\r\nGarnish:\r\n\r\n2 tablespoons sliced green onions\r\n\r\n2 teaspoons sesame seeds', 'Preheat the oven to 425 degrees F (220 degrees C). Line a large baking sheet with foil. Top with a wire rack which has been lightly sprayed with non-stick cooking spray; set aside.\r\n\r\nWhisk baking powder, salt, pepper, garlic powder, and onion powder together in a small bowl. Add mixture to a large resealable plastic bag.\r\n\r\nPat the wings dry with a paper towel, and add some to the bag, shaking and tossing until coated. Shake off excess mixture and set aside. Repeat this procedure with the remaining wings. Place wings on the rack being sure not to overcrowd.\r\n\r\nMove the baking sheet to the oven and cook for 20 minutes. Flip the wings, and bake until browned and crispy, about 15 minutes more. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C). If you want your wings extra crispy, place under the broiler for a couple of minutes. You want them cooked through but still moist, so keep an eye on them to be sure they don&#39;t burn.\r\n\r\nWhile the wings are baking, whisk gochujang, soy sauce, honey, rice vinegar, sesame oil, and ginger powder in a large bowl. When chicken wings are done cooking, immediately add them to the bowl, tossing until all are coated.\r\n\r\nRemove to a serving platter, and garnish with green onions and sesame seeds.', 0x75706c6f6164732f476f6368756a616e6757696e67735f6d656469756d2e6a7067, '2023-03-29 16:03:07', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8544435/gochujang-chicken-wings/', 1),
(108, 'Chimichurri Chicken', '1 cup packed fresh parsley leaves\r\n\r\n2 tablespoons fresh oregano leaves\r\n\r\n1 tablespoon minced garlic\r\n\r\n½ cup chopped green onion (including green tops)\r\n\r\n1 jalapeño pepper, seeds and membranes removed, diced\r\n\r\n2 tablespoons white wine vinegar\r\n\r\n1 tablespoon fresh lemon juice\r\n\r\n½ cup olive oil\r\n\r\nsalt and freshly ground black pepper to taste\r\n\r\n3 pounds chicken tenders\r\n\r\n1 ½ teaspoons smoked paprika', 'Preheat the oven to 375 degrees F (190 degrees C). Line a 12x18-inch sheet pan with parchment or aluminum foil; set aside.\r\n\r\nCombine parsley, oregano, garlic, green onions, and jalapeño in the bowl of a food processor. Pulse just a few times to break up the parsley and combine the ingredients. Place processed vegetables in a small bowl; stir in vinegar, lemon juice, and olive oil. Season with salt and black pepper.\r\n\r\nPlace chicken tenders in a single layer on the prepared pan. Lightly season with salt and pepper; sprinkle smoked paprika evenly over the tenders. Spoon half of the chimichurri evenly over the tenders. Reserve remaining half of chimichurri, covered, in the refrigerator to use later.\r\n\r\nBake in the preheated oven until chicken is no longer pink in the center and the juices run clear, about 18 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).\r\n\r\nServe tenders with reserved chimichurri sauce.', 0x75706c6f6164732f4368696d696368757272692d436869636b656e5f426962695f6d656469756d2e6a7067, '2023-03-29 16:04:22', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8489220/chimichurri-chicken/', 1),
(109, 'Chicken Parmesan Meatballs', '1 large egg, beaten\r\n\r\n¾ cup grated Parmesan cheese\r\n\r\n1 ¾ cups Italian-style panko bread crumbs, divided\r\n\r\n1 teaspoon garlic powder\r\n\r\n1 teaspoon Italian seasoning\r\n\r\n¾ teaspoon crushed red pepper flakes\r\n\r\n½ teaspoon salt\r\n\r\n½ teaspoon freshly ground black pepper\r\n\r\n1 ½ pounds ground chicken\r\n\r\n2 tablespoons olive oil, divided\r\n\r\n2 tablespoons unsalted butter, divided\r\n\r\n1 (28 ounce) jar marinara sauce\r\n\r\n½ cup shredded mozzarella cheese\r\n\r\n2 tablespoons snipped fresh parsley (Optional)', 'Stir egg, grated Parmesan cheese, 3/4 cup panko crumbs, garlic powder, Italian herb seasoning blend, crushed red pepper, salt, and black pepper together in a large bowl.\r\n\r\nPut on a pair of food-grade disposable gloves, add chicken to the bowl, and mix with your hands until all the ingredients are well combined.\r\n\r\nPlace remaining 1 cup panko crumbs on a plate. Using a 1-1/2-inch scoop, create about 24 meatballs. Gently roll each meatball in crumbs until lightly coated; set aside on a plate.\r\n\r\nPreheat oven to 350 degrees F (175 degrees C).\r\n\r\nPlace 1 tablespoon olive oil and 1 tablespoon butter in a large, oven-proof skillet over medium heat. Add half the meatballs and brown each side, turning until all sides are browned. Set this batch on a plate, and wipe the skillet clean.\r\n\r\nRepeat with reserved oil and butter, and cook the remaining meatballs in the same way.\r\n\r\nWipe out the skillet again, and pour in marinara sauce. Place browned meatballs in sauce. They will not be submerged.\r\n\r\nBake in the preheated oven for 25 minutes. Sprinkle on shredded mozzarella and return to the oven for an additional 5 minutes, or until the cheese is melted. Sprinkle with fresh parsley.', 0x75706c6f6164732f5061726d6573616e2d436869636b656e2d4d65617462616c6c735f4269625f6d656469756d2e6a7067, '2023-03-29 16:05:33', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8543745/chicken-parmesan-meatballs/', 1),
(110, 'Southwest Chicken Salad', '1 avocado - peeled, pitted, and chopped\r\n\r\n¼ cup sour cream\r\n\r\n1 tablespoon mayonnaise\r\n\r\n1 tablespoon water\r\n\r\n2 tablespoons freshly squeezed lime juice\r\n\r\n½ (1 ounce) packet ranch dressing mix\r\n\r\n½ teaspoon salt\r\n\r\n2 (6 ounce) skinless, boneless chicken breast halves\r\n\r\n1 tablespoon olive oil\r\n\r\n1 ½ tablespoons fajita seasoning\r\n\r\n1 medium ear corn, husk and silk removed\r\n\r\n1 medium head romaine lettuce, chopped\r\n\r\n½ cup halved grape tomatoes\r\n\r\n1 (15 ounce) can black beans, rinsed and drained\r\n\r\n½ small red onion, sliced into petals', 'Combine avocado, sour cream, mayonnaise, water, lime juice, ranch seasoning, and salt in a food processor. Blend until smooth. Refrigerate until ready to use.\r\n\r\nPlace the chicken in a bowl. Add olive oil and fajita seasoning. Toss until evenly combined.\r\n\r\nPrepare a grill over medium-high heat and lightly oil the grate. Add chicken and corn. Grill, turning once, until corn is tender and chicken is no longer pink in the center and juices run clear, about 10 minutes per side. An instant-read thermometer inserted near the center should read 165 degrees F (74 degrees C). Transfer to a cutting board.\r\n\r\nDivide romaine, tomatoes, black beans, and onions between two serving plates. Cut corn off the cob; divide between the two plates.\r\n\r\nSlice chicken breast; divide between the 2 plates. Drizzle each salad with avocado dressing to serve.', 0x75706c6f6164732f536f757468776573742d436869636b656e2d53616c61645f536f75705f6d656469756d2e6a7067, '2023-03-29 16:09:47', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8508761/southwest-chicken-salad/', 1),
(111, 'Pork Tenderloin with Peaches', '3 slices bacon\r\n\r\n1 (2 pound) package pork tenderloin\r\n\r\n½ teaspoon salt\r\n\r\n¼ teaspoon freshly ground black pepper\r\n\r\n¾ teaspoon ground ginger, divided\r\n\r\n1 ½ cups vertically sliced onion\r\n\r\n1 ½ teaspoons minced garlic\r\n\r\n2 cups peeled and sliced fresh peaches\r\n\r\n1 cup low-sodium chicken broth\r\n\r\n2 tablespoons frozen orange juice concentrate\r\n\r\n1 teaspoon fish sauce\r\n\r\n2 tablespoons water\r\n\r\n2 tablespoons cornstarch\r\n\r\nfresh parsley for garnish (optional)', 'Place bacon in a large skillet and cook over medium-high heat, turning occasionally, until evenly browned and crisp, about 10 minutes. Drain bacon slices on paper towels. Reserve drippings in the skillet.\r\n\r\nDry pork tenderloin with paper towels and season both sides with salt, pepper, and 1/4 teaspoon ground ginger.\r\n\r\nIncrease heat to medium-high and brown tenderloin in the bacon drippings on all sides, 5 to 7 minutes. Removed browned tenderloin from skillet, transfer to a plate, and keep warm.\r\n\r\nReduce heat to medium. Add onion slices to the same skillet and stir until onions are soft and beginning to take on some color, 3 to 5 minutes. Stir in garlic and cook until fragrant, about 1 minute.\r\n\r\nAdd sliced peaches, chicken broth, orange juice concentrate, and remaining ground ginger. Bring to a boil and return tenderloin to the skillet. Pile peaches on top of the meat, cover, reduce heat to simmer, and cook until pork is slightly pink in the center, 20 to 25 minutes. An instant-read thermometer inserted into the center should read at least 145 degrees F (63 degrees C).\r\n\r\nArrange pork and peaches on a serving platter.\r\n\r\nMeanwhile, combine fish sauce, water, and cornstarch in a small bowl and stir until there are no lumps. Increase heat to medium and bring skillet contents back to a boil. Add cornstarch mixture to the liquid in the skillet and stir quickly until sauce is bubbly and thickened, about 5 minutes.\r\n\r\nPour sauce over pork and peaches. Crumble up cooked bacon and sprinkle over the peaches. Garnish with parsley, if desired, and serve warm.', 0x75706c6f6164732f506f726b2d54656e6465726c6f696e2d776974682d506561636865732d426962695f6d656469756d2e6a7067, '2023-03-29 16:12:49', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8420615/pork-tenderloin-with-peaches/', 3),
(112, 'Air Fryer Pork Tenderloin with Sweet Potatoes', '¼ cup olive oil, plus more for greasing\r\n\r\n½ cup pineapple preserves\r\n\r\n½ teaspoon granulated garlic\r\n\r\n½ teaspoon cayenne pepper\r\n\r\n1 teaspoon salt, or to taste\r\n\r\n½ teaspoon freshly ground white pepper, or to taste\r\n\r\n1 ½ pounds sweet potatoes, cut into 1-inch pieces\r\n\r\n2 ½ pounds pork tenderloins', 'Preheat air fryer to 390 degrees F (200 degrees C), if recommended by manufacturer.\r\n\r\nCombine olive oil, pineapple preserves, garlic granules, cayenne, salt, and white pepper in a large mixing bowl; stir to combine.\r\n\r\nPlace sweet potato pieces into the mixing bowl and toss with the pineapple preserves mixture. Remove sweet potatoes to a plate, reserving the remaining pineapple mixture.\r\n\r\nPat tenderloins dry with paper towels. Place in the mixing bowl with the remaining pineapple mixture and toss to coat.\r\n\r\nBrush interior basket of the air fryer with the remaining olive oil. Place tenderloins in the basket, and in a single layer, add as many sweet potato pieces as will fit around the tenderloins. Set aside extra sweet potato pieces. You will cook them as a second batch.\r\n\r\nAir fry for 10 minutes. Turn tenderloins over, browned side down. Stir sweet potatoes, but keep them in a single layer. Air fry until pork loin is slightly pink in the center, about 10 minutes longer. An instant-read thermometer inserted into the center should read at least 145 degrees F (63 degrees C). If the tenderloins need more cooking time, turn them again and continue cooking and testing the temperature in 5 minute increments.\r\n\r\nRemove sweet potatoes from the air fryer when they are tender and caramelized. (See Cook&#39;s Note).\r\n\r\nWhen the tenderloins test done, place them on a platter and tent with foil. Allow to rest while the remaining sweet potatoes cook, about 10 more minutes.', 0x75706c6f6164732f31363733333231393533416972323046727965723230506f726b323054656e6465726c6f696e735f6d656469756d2e6a7067, '2023-03-29 16:13:55', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8529787/air-fryer-pork-tenderloin-with-sweet-potatoes/', 3),
(113, 'Balsamic Braised Pork Tenderloins with Fresh Figs', '2 (1 1/2 pound) pork tenderloins\r\n\r\n1 teaspoon kosher salt, or to taste\r\n\r\n½ teaspoon freshly ground black pepper, or to taste\r\n\r\n2 tablespoons olive oil\r\n\r\n2 shallots, thinly sliced lengthwise\r\n\r\n12 fresh figs, stemmed and halved\r\n\r\n1 cup chicken broth\r\n\r\n¼ cup good-quality balsamic vinegar\r\n\r\n1 tablespoon minced fresh rosemary\r\n\r\nfresh rosemary sprigs for garnish (optional)', 'Preheat the oven to 350 degrees F (175 degrees C).\r\n\r\nPat tenderloins dry and remove silver skin, if present. Season with kosher salt and freshly ground pepper, to taste.\r\n\r\nPour oil into a large, oven-proof skillet and heat over medium-heat until oil shimmers. Carefully place seasoned tenderloins into the hot oil and brown on all sides, 7 to 10 minutes total.\r\n\r\nAdd sliced shallots around tenderloins and stir, about 1 minute. Add figs, chicken broth, and balsamic vinegar. When the mixture begins to bubble, sprinkle minced rosemary over everthing.\r\n\r\nCover, place in the preheated oven and bake until pork is no longer pink in the center, 25 to 30 minutes. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).\r\n\r\nUsing tongs, remove pork from the skillet and place on a serving platter. With a slotted spoon, remove figs from the skillet and place around the tenderloins. Cover loosely with foil.\r\n\r\nPlace skillet back onto the stovetop over medium-high heat. Bring pan juices to a boil and allow to reduce to about 3/4 cup, 10 to 15 minutes.\r\n\r\nSlice tenderloins, drizzle reduced liquid over the meat, and garnish with fresh rosemary sprigs, if desired.', 0x75706c6f6164732f42616c73616d69632d427261697365642d506f726b2d54656e6465726c6f696e732d776974682d46726573682d466967735f6d656469756d2e6a7067, '2023-03-29 16:15:13', '2023-03-31 13:04:47', 'https://www.allrecipes.com/recipe/8465712/balsamic-braised-pork-tenderloins-with-fresh-figs/', 3),
(114, 'Lemon Pork with Mushrooms', '1 large egg, lightly beaten\r\n1 cup seasoned bread crumbs\r\n8 thin boneless pork loin chops (2 ounces each)\r\n1/4 teaspoon salt\r\n1/8 teaspoon pepper\r\n1 tablespoon olive oil\r\n1 tablespoon butter\r\n1/2 pound sliced fresh mushrooms\r\n2 garlic cloves, minced\r\n2 teaspoons grated lemon zest\r\n1 tablespoon lemon juice\r\nLemon wedges, optional', 'Place egg and bread crumbs in separate shallow bowls. Sprinkle pork chops with salt and pepper; dip in egg, then coat with crumbs, pressing to adhere.\r\nIn a large skillet, heat oil over medium heat. In batches, cook pork until golden brown, 2-3 minutes per side. Remove from pan; keep warm.\r\nWipe pan clean. In skillet, heat butter over medium heat; saute mushrooms until tender, 2-3 minutes. Stir in garlic, lemon zest and lemon juice; cook and stir 1 minute. Serve over pork. If desired, serve with lemon wedges.', 0x75706c6f6164732f4c656d6f6e2d506f726b2d776974682d4d757368726f6f6d732d5f6d656469756d2e6a7067, '2023-03-31 18:47:34', '2023-03-31 14:21:08', 'https://www.tasteofhome.com/recipes/lemon-pork-with-mushrooms/', 3),
(115, 'Beef Tenderloin in Mushroom Sauce', 'Beef Tenderloin in Mushroom Sauce', 'In a large skillet, heat 2 tablespoons butter and oil over medium-high heat; cook steaks to desired doneness (for medium-rare, a thermometer should read 135°; medium, 140°), 5-6 minutes per side. Remove from pan, reserving drippings; keep warm.\r\nIn same pan, heat drippings and remaining butter over medium-high heat; saute mushrooms and green onion until tender. Stir in flour, salt and pepper until blended; gradually stir in broth and, if desired, browning sauce. Bring to a boil, stirring constantly; cook and stir until thickened, 1-2 minutes. Serve with steaks.', 0x75706c6f6164732f426565662d54656e6465726c6f696e2d696e2d4d757368726f6f6d2d53617563655f5f6d656469756d2e6a7067, '2023-03-29 16:26:41', '2023-03-31 13:04:47', 'https://www.tasteofhome.com/recipes/beef-tenderloin-in-mushroom-sauce/', 2),
(116, 'Sesame Beef Skewers', '1 pound beef top sirloin steak, cut into 1-inch cubes\r\n6 tablespoons sesame ginger salad dressing, divided\r\n1 tablespoon reduced-sodium soy sauce\r\n2 cups chopped fresh pineapple\r\n2 medium apples, chopped\r\n1 tablespoon sweet chili sauce\r\n1 tablespoon lime juice\r\n1/4 teaspoon pepper\r\n1 tablespoon sesame seeds, toasted', 'In a bowl, toss beef with 3 tablespoons dressing and soy sauce; let stand 10 minutes. Meanwhile, in a large bowl, combine pineapple, apples, chili sauce, lime juice and pepper; toss to combine.\r\nThread beef onto 4 metal or soaked wooden skewers; discard remaining marinade. Grill kabobs, covered, over medium heat or broil 4 in. from heat until desired doneness, 7-9 minutes, turning occasionally; brush generously with remaining dressing during the last 3 minutes. Sprinkle with sesame seeds. Serve with pineapple mixture.', 0x75706c6f6164732f62656566736b65776572735f6d656469756d2e6a7067, '2023-03-29 16:27:38', '2023-03-31 13:04:47', 'https://www.tasteofhome.com/recipes/sesame-beef-skewers/', 2),
(117, 'Weeknight Beef Skillets', '3 cups uncooked yolk-free whole wheat noodles\r\n1 pound lean ground beef (90% lean)\r\n1 medium green pepper, finely chopped\r\n1 can (15 ounces) tomato sauce\r\n1 tablespoon Worcestershire sauce', 'Cook noodles according to package directions; drain. Meanwhile, in a large nonstick skillet, cook beef and pepper over medium heat 5-7 minutes or until beef is no longer pink, breaking up beef into crumbles; drain.\r\nAdd tomato sauce, Worcestershire sauce, Italian seasoning and, if desired, sugar to beef mixture; bring to a boil. Stir in vegetables; heat through. Serve with noodles; sprinkle with parsley.', 0x75706c6f6164732f62656566736b696c6c65745f6d656469756d2e6a7067, '2023-03-29 16:28:30', '2023-04-05 16:19:32', 'https://www.tasteofhome.com/recipes/weeknight-beef-skillet/', 2),
(118, 'Beef Raguss', '2 tablespoons olive oil\r\n\r\n1 (2 pound) boneless beef chuck roast, cut into 2-inch cubes\r\n\r\n1 teaspoon ground black pepper\r\n\r\n3 teaspoons kosher salt, divided\r\n\r\n1 yellow onion, chopped\r\n\r\n6 cloves garlic, chopped\r\n\r\n2 tablespoons harissa (Optional)\r\n\r\n2 tablespoons tomato paste\r\n\r\n1 cup dry red wine\r\n\r\n1 (28 ounce) can crushed tomatoes\r\n\r\n1 bay leaf\r\n\r\n1 pound pappardelle pasta, cooked and drained\r\n\r\ngrated Parmesan cheese, for serving', 'Heat oil in a large Dutch oven over medium-high. Season chuck roast with pepper and 2 teaspoons salt. Sear meat until browned on every side, working in batches if necessary, about 10 minutes. Remove from Dutch oven and transfer to a large plate.\r\n\r\nReduce heat to medium and stir in onion. Cook, stirring often, until softened, about 8 minutes. Add garlic and cook, stirring constantly, until fragrant, about 1 minute. Stir in harissa and tomato paste; cook, stirring constantly, until caramelized, about 2 minutes.\r\n\r\nPour in wine and cook, scraping the bottom of the pot with a wooden spoon to loosen any browned bits, until reduced by two thirds, about 5 minutes. Stir in tomatoes, bay leaf, chuck roast, and remaining 1 teaspoon salt. Reduce heat to medium-low and cover. Cook, stirring occasionally, until meat is tender, sauce has thickened, and flavors meld, about 2 1/2 hours.\r\n\r\nRemove and discard bay leaf. Transfer meat from Dutch oven to a cutting board and shred using 2 forks. Return meat to pot and stir in pappardelle. Top with grated Parmesan cheese.', 0x75706c6f6164732f626565662d726167755f6d656469756d2e6a7067, '2023-03-31 19:17:38', '2023-03-31 15:39:26', 'https://www.allrecipes.com/recipe/8465557/beef-ragu/', 2),
(150, 'Coconut Creamed Spinach', '1 tablespoon olive oil\r\n\r\n4 ounces sliced baby bella mushrooms\r\n\r\n1 medium shallot, minced\r\n\r\n2 cloves garlic, minced\r\n\r\n8 cups raw spinach leaves\r\n\r\n1 cup full-fat coconut milk\r\n\r\n2 teaspoons white wine vinegar\r\n\r\nsalt and freshly ground black pepper to taste\r\n\r\nfreshly-grated nutmeg (optional)', 'Heat olive oil in a large skillet over medium heat. Add the mushrooms, shallot, and garlic and cook, stirring occasionally, until soft and fragrant, about 3 minutes.\r\n\r\nGradually add spinach by handfuls, stirring until it wilts. Continue until all the spinach is in the skillet, about 5 minutes.\r\n\r\nGradually pour in coconut milk and vinegar and bring to a simmer. Simmer until mixture thickens, 4 to 5 minutes.\r\n\r\nSeason with salt, pepper, and a sprinkle of freshly ground nutmeg. Serve immediately.', 0x75706c6f6164732f436f636f6e75742d437265616d65642d5370696e6163685f6d656469756d2e6a7067, '2023-04-10 17:17:20', '2023-04-10 12:17:20', 'https://www.allrecipes.com/recipe/8461550/coconut-creamed-spinach/', 4),
(151, 'Garlic Sautéed Vegetables', '1 tablespoon olive oil\r\n\r\n½ cup diced red bell pepper (1-inch)\r\n\r\n1 ½ cups thickly sliced cauliflower florets\r\n\r\n1 medium yellow squash, halved and sliced\r\n\r\n2 cloves garlic, minced\r\n\r\n1 cup Swanson® Chicken Broth', 'Heat the oil in a 12-inch skillet over high heat. Add the red pepper, cauliflower, green beans, and squash and cook for 4 minutes or until lightly browned, stirring occasionally.\r\n\r\nAdd the garlic to the skillet and cook and stir for 1 minute. Add Swanson® Chicken Broth and heat to a boil, stirring to scrape up the browned bits from the bottom of the skillet. Reduce the heat to medium-high. Cook for 3 minutes or until the vegetables are tender, stirring occasionally. Season to taste.', 0x75706c6f6164732f4761726c69632d536175746565642d566567657461626c65735f6d656469756d2e6a7067, '2023-04-10 17:19:13', '2023-04-10 12:19:13', 'https://www.allrecipes.com/recipe/8468938/garlic-sauteed-vegetables/', 4),
(152, 'Kabobs', '½ cup teriyaki sauce\r\n\r\n½ cup honey\r\n\r\n½ teaspoon garlic powder\r\n\r\n½ pinch ground ginger\r\n\r\n1 ½ pounds skinless, boneless chicken breast halves - cut into cubes\r\n\r\n1 pound beef sirloin, cut into 1 inch cubes\r\n\r\n2 red bell peppers, cut into 2 inch pieces\r\n\r\n1 large sweet onion, peeled and cut into wedges\r\n\r\n1 ½ cups whole fresh mushrooms\r\n\r\nskewers', 'Mix teriyaki sauce, honey, garlic powder, and ginger in a large resealable plastic bag. Place chicken, beef, red bell peppers, onion wedges, and mushrooms in the bag, coat with the marinade, squeeze out excess air, and seal the bag. Refrigerate for 4 hours to overnight.\r\n\r\nPreheat the grill to medium-high heat. Lightly oil the grill grate.\r\n\r\nDiscard marinade. Thread meat and vegetables onto skewers, leaving a small space between each item.\r\n\r\nGrill skewers, turning as needed, until meat is cooked through and vegetables are tender, about 10 minutes.', 0x75706c6f6164732f6b61626f62735f6d656469756d2e6a7067, '2023-04-10 17:22:05', '2023-04-10 12:22:05', 'https://www.allrecipes.com/recipe/17904/kabobs/', 1),
(153, 'Chicken Katsu', '4 skinless, boneless chicken breast halves - pounded to 1/2 inch thickness\r\n\r\nsalt and pepper to taste\r\n\r\n2 tablespoons all-purpose flour\r\n\r\n1 egg, beaten\r\n\r\n1 cup panko bread crumbs\r\n\r\n1 cup oil for frying, or as needed', 'Season chicken breasts on both sides with salt and pepper. Place flour, beaten egg, and panko crumbs into separate shallow dishes. Coat chicken breasts in flour, shaking off any excess; dip into egg, and then press into panko crumbs until well coated on both sides.\r\n\r\nHeat oil in a large skillet over medium-high heat. Place chicken in the hot oil, and fry until golden brown, 3 or 4 minutes per side. Transfer to a paper towel-lined plate to drain.', 0x75706c6f6164732f636869636b656e5f6b617473755f6d656469756d2e6a7067, '2023-04-10 17:23:40', '2023-04-10 12:23:40', 'https://www.allrecipes.com/recipe/72068/chicken-katsu/', 1),
(154, 'Sous Vide Beef Tenderloin Roast', '4 ½ pounds whole beef tenderloin\r\n\r\n1 tablespoon sea salt/kosher salt (such as Redmonds®)\r\n\r\n1 teaspoon freshly ground black pepper, or more to taste\r\n\r\n6 cloves garlic\r\n\r\n3 fresh thyme sprigs, or to taste\r\n\r\nrosemary sprig\r\n\r\n3 tablespoons unsalted butter, divided, or more as needed\r\n\r\n2 tablespoons olive oil, or as needed\r\n\r\n1 splash red wine\r\n\r\n1 tablespoon gelatin powder\r\n\r\n1 cup cold water\r\n\r\nsalt and freshly ground black pepper to taste', 'Trim and tie tenderloin together with kitchen twine the night before cooking. Combine salt and pepper in a bowl and season tenderloin on all sides. Place on a baking rack set over a cookie sheet and allow to rest, uncovered, in the refrigerator overnight.\r\n\r\nThe next morning place tenderloin, garlic, thyme, and rosemary into a sous vide vacuum bag and seal using a vacuum sealer. Refrigerate until you are ready to sous vide.\r\n\r\nAttach sous vide cooker to a heat-proof container of water and set temperature to 133 degrees F (56 degrees C). Sous vide until tenderloin has reached the desired temperature, 2 1/2 to 3 hours, depending on thickness.\r\n\r\nAbout 30 minutes pour water in a metal bowl and sprinkle gelatin powder on top. Allow to sit for 30 minutes until gelatin blooms. Set on top of a double boiler over simmering water and stir until a clear liquid forms. Do not allow to boil.\r\n\r\nRemove tenderloin from sous vide, pat dry, and let rest while preparing the gravy.\r\n\r\nPour au jus liquids from the sous vide bag into a sauce pan. Stir in 1 to 2 tablespoons butter and red wine. Add as much of the bloomed gelatin as you like depending on desired thickness and whisk until well combined. Season gravy with salt, pepper, and herbs to taste.\r\n\r\nHeat cast iron pan to medium-high. Brush tenderloin with olive oil and sear in the hot pan until browned all over, 1 to 2 minutes per side. Melt extra butter in the pan as desired. Remove from pan, tent with foil, and allow to rest for 5 to 10 minutes.\r\n\r\nSlice tenderloin and serve with gravy.\r\n\r\n', 0x75706c6f6164732f62656566323074656e6465726c6f696e3230726f6173745f6d656469756d2e6a7067, '2023-04-10 17:24:58', '2023-04-10 12:24:58', 'https://www.allrecipes.com/recipe/8524014/sous-vide-beef-tenderloin-roast/', 2),
(155, 'Quick Beef Stir-Fry', 'Ingredients\r\n2 tablespoons vegetable oil\r\n\r\n1 pound beef sirloin, cut into 2-inch strips\r\n\r\n1 ½ cups fresh broccoli florets\r\n\r\n1 red bell pepper, cut into matchsticks\r\n\r\n2 carrots, thinly sliced\r\n\r\n1 green onion, chopped\r\n\r\n1 teaspoon minced garlic\r\n\r\n2 tablespoons soy sauce\r\n\r\n2 tablespoons sesame seeds, toasted', 'Gather all ingredients.\r\n\r\nOverhead of stir-fry ingredients in various bowls. \r\n\r\nHeat vegetable oil in a large wok or skillet over medium-high heat; cook and stir beef until browned, 3 to 4 minutes.\r\n\r\nOverhead of beef being cooked in a wok. \r\nMove beef to the side of the wok and add broccoli, bell pepper, carrots, green onion, and garlic to the center of the wok. Cook and stir vegetables for 2 minutes.\r\n\r\nStir beef into vegetables and season with soy sauce and sesame seeds. Continue to cook and stir until vegetables are tender, about 2 more minutes.\r\n\r\nOverhead of chopped vegatables, beef, and seseme seeds being cooked together in a wok. \r\n\r\nServe hot and enjoy!', 0x75706c6f6164732f62656566737469726672795f6d656469756d2e6a7067, '2023-04-10 17:26:52', '2023-04-10 12:27:22', 'https://www.allrecipes.com/recipe/228823/quick-beef-stir-fry/', 2),
(156, 'World&#39;s Best Honey Garlic Pork Chops', 'World&#39;s Best Honey Garlic Pork Chops', 'Preheat grill for medium heat and lightly oil the grate. Gather ingredients.\r\n\r\nFour raw, bone-in pork chops on a baking sheet with 4 small bowls of ingredients on the side\r\nWhisk ketchup, honey, soy sauce, and garlic together in a bowl to make a glaze.\r\n\r\nOverhead view of brown sauce inside of a clear glass bowl and a hand with a whisk stirring said sauce\r\nSear the pork chops on both sides on the preheated grill. Lightly brush glaze onto each side of the chops as they cook; grill until no longer pink in the center, about 7 to 9 minutes per side. An instant-read thermometer inserted into the center should read 145 degrees F (63 degrees C).\r\n\r\nOverhead view of 4 pork chops on a griddle. Brush with sauce on the surface of one of the pork chops.\r\nServe hot and enjoy!', 0x75706c6f6164732f6761726c6963706f726b63686f70735f6d656469756d2e6a7067, '2023-04-10 17:30:04', '2023-04-10 12:30:04', 'https://www.allrecipes.com/recipe/235158/worlds-best-honey-garlic-pork-chops/', 3),
(157, ' Air Fryer Buffalo Cauliflower', '½ cup Buffalo wing sauce (such as Frank&#39;s®)\r\n\r\n1 tablespoon butter, melted\r\n\r\n1 teaspoon honey\r\n\r\n1 (2 pound) cauliflower, broken into florets\r\n\r\n¼ cup all-purpose flour\r\n\r\n¼ cup cornstarch\r\n\r\n1 teaspoon garlic powder\r\n\r\n½ teaspoon seasoned salt (such as LAWRY&#39;S®)\r\n\r\n¼ teaspoon paprika\r\n\r\ndrizzle of buffalo wing sauce (optional)', 'Combine hot sauce, butter, and honey in a large bowl, and whisk until well combined. Add cauliflower florets and stir until well coated.\r\n\r\nCombine flour, cornstarch, garlic powder, seasoning salt, and paprika in a separate bowl, stirring well. Gradually sprinkle the flour mixture over the cauliflower florets, tossing until all florets are coated.\r\n\r\nPreheat the air fryer to 390 degrees F (195 degrees C). Spray the fryer basket with olive oil spray or line with a parchment liner.\r\n\r\nTransfer cauliflower florets to the air fryer basket in a single layer, making sure not to overcrowd the basket, so they&#39;ll crisp up and not turn soggy.\r\n\r\nAir fry for 10 to 15 minutes, shaking the basket several times until the florets are lightly browned. They should be crispy, but not overcooked or mushy. You may have to cook in batches depending on the size of your air fryer. Time may vary depending on the size and brand of your air fryer.\r\n\r\nGive the cauliflower a light drizzle of buffalo wing sauce when they come out of the air fryer, if desired. Serve with your choice of a creamy dipping sauce.', 0x75706c6f6164732f4169722d46727965722d42756666616c6f2d4361756c69666c6f7765725f6d656469756d2e6a7067, '2023-04-10 17:32:28', '2023-04-10 12:32:28', 'https://www.allrecipes.com/recipe/8537905/air-fryer-buffalo-cauliflower/', 4),
(158, 'Roasted Acorn Squash with Sriracha Butter', '1 (2 pound) acorn squash\r\n\r\n¼ cup butter\r\n\r\n2 tablespoons Sriracha sauce\r\n\r\n2 teaspoons honey\r\n\r\n1 tablespoon olive oil\r\n\r\nsalt and freshly ground black pepper to taste', 'Preheat the oven to 400 degrees F (200 degrees C). Line a baking sheet with parchment paper.\r\n\r\nCut the squash in half vertically, and scoop out the seeds in the middle. Cut each half into 4 wedges and place wedges on the prepared baking sheet.\r\n\r\nMelt butter in a small saucepan over medium-low heat. Whisk in Sriracha sauce and honey; keep warm.\r\n\r\nBrush squash with olive oil and sprinkle with salt and pepper. Place wedges on their side and roast for 20 minutes; flip wedges over and roast until squash is soft and edges are caramelized, 15 to 20 minutes.\r\n\r\nPlace wedges on a serving platter and drizzle with Sriracha butter.', 0x75706c6f6164732f7371756173685f6d656469756d2e6a7067, '2023-04-10 17:33:33', '2023-04-10 12:33:33', 'https://www.allrecipes.com/recipe/8513732/roasted-acorn-squash-with-sriracha-butter/', 4),
(159, 'Honey-Lemon Roasted Carrot Salad', '2 pounds carrots, peeled and bias-sliced\r\n\r\n3 tablespoons olive oil, divided\r\n\r\n3 cloves garlic, sliced\r\n\r\n2 tablespoons lemon juice\r\n\r\n2 teaspoons honey\r\n\r\n¼ teaspoon salt\r\n\r\n¼ teaspoon freshly ground black pepper\r\n\r\n2 cups arugula\r\n\r\n⅓ cup dried cranberries\r\n\r\n2 tablespoons dry roasted sunflower seeds\r\n\r\nshaved Parmesan cheese', 'Preheat the oven to 400 degrees F (200 degrees C).\r\n\r\nDivide carrots between two 10x15-inch baking pans. Drizzle with 1 tablespoon oil per pan; toss to coat.\r\n\r\nRoast carrots until soft and starting to brown, stirring occasionally, about 20 minutes. Top with sliced garlic and roast 5 minutes more. Let cool 15 minutes.\r\n\r\nMeanwhile, whisk together lemon juice, honey, salt, pepper, and remaining 1 tablespoon oil in an extra-large bowl. Add roasted carrots, arugula, and cranberries; toss to coat. Top with sunflower seeds and shaved Parmesan.', 0x75706c6f6164732f686f6e65796c656d6f6e636172726f745f6d656469756d2e6a7067, '2023-04-10 17:34:45', '2023-04-10 12:34:45', 'https://www.allrecipes.com/recipe/8489333/honey-lemon-roasted-carrot-salad/', 4),
(160, 'Traditional Filipino Lumpia', '1 tablespoon vegetable oil\r\n\r\n1 pound ground pork\r\n\r\n½ cup chopped onion\r\n\r\n2 cloves garlic, crushed\r\n\r\n½ cup minced carrots\r\n\r\n½ cup chopped green onions\r\n\r\n½ cup thinly sliced green cabbage\r\n\r\n2 tablespoons chopped fresh cilantro (Optional)\r\n\r\n1 teaspoon ground black pepper\r\n\r\n1 teaspoon salt\r\n\r\n1 teaspoon garlic powder\r\n\r\n1 teaspoon soy sauce\r\n\r\n30 lumpia wrappers\r\n\r\n2 cups vegetable oil for frying, or as needed', 'Heat 1 tablespoon vegetable oil in a wok or large skillet over high heat. Add pork; cook and stir until crumbly and no pink is showing, 5 to 7 minutes. Remove pork from the pan and set aside. Drain grease from the pan, leaving just a thin coating.\r\n\r\nAdd onion and garlic to the pan; cook and stir until fragrant, about 2 minutes. Stir in the cooked pork, carrots, green onions, cabbage, and cilantro. Season with pepper, salt, garlic powder, and soy sauce. Remove from the heat, and set aside until cool enough to handle, about 5 minutes.\r\n\r\nAssemble lumpia: Place 3 heaping tablespoons of filling diagonally near one corner of a lumpia wrapper, leaving a 1 1/2 inch space at both ends. Fold the side along the length of the filling over the filling, tuck in both ends, and roll neatly and tightly to close. Moisten the other side of the wrapper with water to seal the edge. Transfer to a plate and cover with plastic wrap to retain moisture. Repeat to assemble remaining lumpia.\r\n\r\nHeat 1/2 inch vegetable oil in a heavy skillet over medium heat for 5 minutes.\r\n\r\nSlide 3 to 4 lumpia into the hot oil, making sure the seams are facing down. Fry, turning occasionally, until all sides are golden brown, 1 to 2 minutes. Transfer to a paper towel-lined plate to drain. Repeat to fry remaining lumpia. Serve immediately.', 0x75706c6f6164732f6c756d7069615f6d656469756d2e6a7067, '2023-04-10 17:36:43', '2023-04-10 12:36:43', 'https://www.allrecipes.com/recipe/35151/traditional-filipino-lumpia/', 4),
(161, 'Easy Marinated Pork Tenderloins', '¼ cup olive oil\r\n\r\n¼ cup soy sauce\r\n\r\n1 clove garlic, minced\r\n\r\n3 tablespoons Dijon honey mustard\r\n\r\nsalt and ground black pepper to taste\r\n\r\n2 pounds pork tenderloin', 'Whisk olive oil, soy sauce, garlic, mustard, salt, and pepper together in a bowl.\r\n\r\nOlive oil, soy sauce, garlic, mustard, salt, and pepper whisked together in a bowl.\r\nPlace pork in a large resealable plastic bag and pour in marinade; squeeze out excess air, and seal the bag. Marinate in the refrigerator at least 1 hour before cooking.\r\n\r\nPork tenderloin placed in a bag with marinade poured in.\r\nPreheat the oven to 350 degrees F (175 degrees C).\r\n\r\nTransfer pork to a baking dish; pour marinade over the pork.\r\n\r\nPork tenderloin placed in a baking dish with marinade poured over.\r\n\r\nCook in the preheated oven until pork is slightly pink in the center, about 45 to 60 minutes. An instant-read thermometer inserted into the center should read at least 145 degrees F (63 degrees C).', 0x75706c6f6164732f6d6172696e61746564706f726b74656e6465726c6f696e5f6d656469756d2e6a7067, '2023-04-10 17:39:12', '2023-04-11 17:21:44', 'https://www.allrecipes.com/recipe/176359/easy-marinated-pork-tenderloin/', 3);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`recipe_id`),
  ADD KEY `categoryID_FK` (`categories_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `recipe_id` int(250) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=177;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `recipes`
--
ALTER TABLE `recipes`
  ADD CONSTRAINT `categoryID_FK` FOREIGN KEY (`categories_id`) REFERENCES `categories` (`categories_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
